const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

const rootDir = path.resolve(__dirname, '..', '..', '..');
const postsTemplate = fs.readFileSync(path.join(rootDir, 'templates', 'posts.twig'), 'utf8');
const siteCss = fs.readFileSync(path.join(rootDir, 'web', 'css', 'site.css'), 'utf8');
const styleGuide = fs.readFileSync(path.join(rootDir, 'templates', 'style-guide.twig'), 'utf8');

test('posts archive template renders the expected panel content and filters', () => {
  assert.match(postsTemplate, /featuredImage\s*\?\s*entry\.featuredImage\.one\(\)\s*:\s*null/);
  assert.match(postsTemplate, /<img class="thumb" src="\{\{\s*image\.url\s*\}\}" alt="\{\{\s*image\.title\s*\?:\s*entry\.title\s*\}\}">/);
  assert.match(postsTemplate, /<h3><a href="\{\{\s*entry\.url\s*\}\}">\{\{\s*entry\.title\s*\}\}<\/a><\/h3>/);
  assert.match(postsTemplate, /entry\.postDate\|date\('F Y'\)/);
  assert.match(postsTemplate, /name="projectType\[\]"/);
  assert.match(postsTemplate, /name="category\[\]"/);
  assert.match(postsTemplate, /name="tag\[\]"/);
  assert.match(postsTemplate, /name="year\[\]"/);
  assert.match(postsTemplate, /panel-category-chips/);
  assert.match(postsTemplate, /class="chip color-pair-\{\{\s*entryProjectTypeChip\.colourPair\s*\}\}"/);
  assert.match(postsTemplate, /class="chip color-pair-\{\{\s*entryDesignSource\.colourPair\s*\}\}"/);
  assert.match(postsTemplate, /class="chip color-pair-\{\{\s*attribute\(category,\s*'colourPair'\)\s*\}\}"/);
  assert.match(postsTemplate, /attribute\(category,\s*'colourPair'\)/);
  assert.match(postsTemplate, /\?category\[\]=\{\{\s*category\.slug\|url_encode\s*\}\}/);
  assert.match(postsTemplate, /selectedProjectTypeSlugs/);
  assert.match(postsTemplate, /selectedTagSlugs/);
  assert.match(postsTemplate, /selectedYears/);
  assert.doesNotMatch(postsTemplate, /categoryChipColor/);
  assert.doesNotMatch(postsTemplate, /projectTypeColorPairs/);
  assert.doesNotMatch(postsTemplate, /designSourceSlug/);
  assert.doesNotMatch(postsTemplate, /muted-(gold|sand|sage|olive|sky|stone|rose|clay|plum|ink)/);
  assert.doesNotMatch(postsTemplate, /panel-category-chip\b/);
  assert.doesNotMatch(postsTemplate, /panel-type-chip--/);
  assert.doesNotMatch(postsTemplate, /panel-design-source-chip--/);
});

test('site CSS encodes the archive typography and panel layout rules', () => {
  assert.match(siteCss, /--font-body:\s*"Open Sans",\s*sans-serif;/);
  assert.match(siteCss, /--font-heading:\s*"Playfair Display",\s*serif;/);
  assert.match(siteCss, /--font-brand:\s*"Dancing Script",\s*cursive;/);
  assert.match(siteCss, /\.chip\s*\{[\s\S]*display:\s*inline-block;/);
  assert.match(siteCss, /--color-pair-gold-bg:\s*#efe9da;/);
  assert.match(siteCss, /--color-pair-sand-bg:\s*#f3efe6;/);
  assert.match(siteCss, /--color-pair-sage-bg:\s*#edf2ea;/);
  assert.match(siteCss, /--color-pair-olive-bg:\s*#e7eee2;/);
  assert.match(siteCss, /--color-pair-stone-bg:\s*#edf0f2;/);
  assert.match(siteCss, /--color-pair-rose-bg:\s*#f6e6e2;/);
  assert.match(siteCss, /--color-pair-sky-bg:\s*#e7eef5;/);
  assert.match(siteCss, /--color-pair-clay-bg:\s*#f3e5dc;/);
  assert.match(siteCss, /--color-pair-plum-bg:\s*#ece7f3;/);
  assert.match(siteCss, /--color-pair-ink-bg:\s*#e8ebf1;/);
  assert.match(siteCss, /--color-pair-moss-bg:\s*#e1e9d9;/);
  assert.match(siteCss, /--color-pair-lavender-bg:\s*#e8e3f0;/);
  assert.match(siteCss, /--color-pair-peach-bg:\s*#f5e8df;/);
  assert.match(siteCss, /--color-pair-slate-bg:\s*#e2e6eb;/);
  assert.match(siteCss, /--color-pair-rust-bg:\s*#f0e3db;/);
  assert.match(siteCss, /--color-pair-berry-bg:\s*#efe2e6;/);
  assert.match(siteCss, /\.color-pair-gold\s*\{[\s\S]*background:\s*var\(--color-pair-gold-bg\);/);
  assert.match(siteCss, /\.color-pair-ink\s*\{[\s\S]*background:\s*var\(--color-pair-ink-bg\);/);
  assert.match(siteCss, /\.color-pair-berry\s*\{[\s\S]*background:\s*var\(--color-pair-berry-bg\);/);
  assert.match(siteCss, /h3\s*\{[\s\S]*font-size:\s*var\(--type-h3\);/);
  assert.match(siteCss, /\.panel-excerpt\s*\{[\s\S]*-webkit-line-clamp:\s*3;/);
  assert.match(siteCss, /\.subtitle\s*\{[\s\S]*text-transform:\s*uppercase;/);
  assert.match(siteCss, /\.caption\s*\{[\s\S]*font-size:\s*var\(--type-caption\);/);
  assert.doesNotMatch(siteCss, /\.chip\.color-pair-|\.color-pair-muted-/);
  assert.doesNotMatch(siteCss, /panel-category-chip\b/);
  assert.doesNotMatch(siteCss, /panel-type-chip--/);
  assert.doesNotMatch(siteCss, /panel-design-source-chip--/);
});

test('template and CSS still advertise the visible project archive chrome', () => {
  assert.match(postsTemplate, /<aside class="sidebar">/);
  assert.match(postsTemplate, /<div class="container-section-header">Project Type<\/div>/);
  assert.match(postsTemplate, /<div class="container-section-header">Categories<\/div>/);
  assert.match(postsTemplate, /<div class="container-section-header">Tags<\/div>/);
  assert.match(postsTemplate, /<div class="container-section-header">Year<\/div>/);
  assert.match(siteCss, /\.page-layout\s*\{/);
  assert.match(siteCss, /\.grid\s*\{/);
});

test('style guide shows every reusable colour pair', () => {
  assert.match(styleGuide, /set colourPairs = \[/);
  assert.match(styleGuide, /color-pair-gold/);
  assert.match(styleGuide, /Muted Gold/);
  assert.match(styleGuide, /color-pair-sand/);
  assert.match(styleGuide, /Muted Sand/);
  assert.match(styleGuide, /color-pair-sage/);
  assert.match(styleGuide, /Muted Sage/);
  assert.match(styleGuide, /color-pair-olive/);
  assert.match(styleGuide, /Muted Olive/);
  assert.match(styleGuide, /color-pair-sky/);
  assert.match(styleGuide, /Muted Sky/);
  assert.match(styleGuide, /color-pair-stone/);
  assert.match(styleGuide, /Muted Stone/);
  assert.match(styleGuide, /color-pair-rose/);
  assert.match(styleGuide, /Muted Rose/);
  assert.match(styleGuide, /color-pair-clay/);
  assert.match(styleGuide, /Muted Clay/);
  assert.match(styleGuide, /color-pair-plum/);
  assert.match(styleGuide, /Muted Plum/);
  assert.match(styleGuide, /color-pair-ink/);
  assert.match(styleGuide, /Muted Ink/);
  assert.match(styleGuide, /color-pair-moss/);
  assert.match(styleGuide, /Muted Moss/);
  assert.match(styleGuide, /color-pair-lavender/);
  assert.match(styleGuide, /Muted Lavender/);
  assert.match(styleGuide, /color-pair-peach/);
  assert.match(styleGuide, /Muted Peach/);
  assert.match(styleGuide, /color-pair-slate/);
  assert.match(styleGuide, /Muted Slate/);
  assert.match(styleGuide, /color-pair-rust/);
  assert.match(styleGuide, /Muted Rust/);
  assert.match(styleGuide, /color-pair-berry/);
  assert.match(styleGuide, /Muted Berry/);
});
