allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  0e85e74b-5f9f-406c-883d-a9d91b8333de:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-01T16:15:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 672dca83-46cd-4ac4-aa4b-65e9d7430d7a # Home Card Image
            handle: null
            instructions: null
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93ebdf07-80de-4363-8660-6f6335f6ddfe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-01T16:15:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 101aedec-3a1b-481f-b8ae-4522481936b6 # Home Card Text
            handle: null
            instructions: null
            label: Text
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb6e4653-d082-418a-a0e9-883cfb31527d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-01T16:15:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5d7b7d6f-0d18-4dc2-988c-01f4d2f0b4f4 # Home Card Link
            handle: null
            instructions: null
            label: Link
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fb7af0d-0bc0-47df-b1d3-6f3c8eb8ef4d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8ae2d5a-8cf2-4dd2-8d2f-7b1c35e2e3f1
        userCondition: null
    thumbFieldKey: null
handle: homeCard
hasTitleField: false
icon: null
name: 'Home Card'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
