allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  5c3a73a0-7d1a-4d56-b67d-029b097b407d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2eeb9770-728d-420e-8988-faf46168b929 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e41f68b-6a6c-44a7-bcb9-314e56aa9e91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 88e54dd6-f463-4cc9-9d1f-a3014a370157 # Text Blocks
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c50fd2c-ac92-4d7d-8390-25abb6099f5c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7aaf5bac-b1fe-47f3-a96f-faa658d8d7ab
        userCondition: null
    thumbFieldKey: null
handle: instructionStep
hasTitleField: false
icon: null
name: 'Instruction Step'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
