allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f04972c9-669b-485e-a86d-6a0723c75123:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-27T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: de28d2f7-8a33-44e7-801e-e65a0c589c14 # Heading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcbccc7f-b0f0-4849-b938-edf6406d6b4e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c00d971d-29eb-48e9-af14-1438acd199a0 # Subheading
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab6d9753-80c8-4d64-9475-33d9b445a94f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3b128811-957e-40d4-aeb7-ca8c63f7e1de # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5ae7362-89d7-460e-a5c0-8391e1b12ebb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-27T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 770e7672-f720-4f28-8d28-ec42a350e7c8 # Instruction Steps
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aade9d77-c4ea-4a1c-900b-e35787486798
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 245b2798-2864-433e-8c7b-896984eb6e61
        userCondition: null
    thumbFieldKey: null
handle: instructionSection
hasTitleField: false
icon: null
name: 'Instruction Section'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{instructionSectionHeading}'
