allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  c45f1bd1-69a0-4bc3-8956-1f559cbf4cd4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-06-22T00:00:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 677507b9-ba5d-4ee3-9164-3e2c3013a281
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-22T12:59:58+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 988f6d4d-f99d-4996-a981-d3f4e7569f59 # Directory
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af1f5772-5341-40a3-9231-57af0072b401
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-22T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b0fd993f-201f-421a-973d-1c61f5c12903 # Markdown Source URL
            handle: null
            instructions: null
            label: 'Content URL'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f3a9f74-b76c-4fc8-8a39-3b5ff6c0c02b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 57d1f2a6-2c40-40a0-b7e8-33d0de88ad72
        userCondition: null
    thumbFieldKey: null
handle: markdownPage
hasTitleField: true
icon: null
name: 'Markdown Page'
showSlugField: true
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
