allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  536a24e2-784e-4b9e-b5fb-03be4a218d74:
    cardThumbAlignment: end
    generatedFields:
      -
        handle: ''
        name: ''
        template: ''
        uid: 9751cba1-03f3-42dc-9149-c6737d3871e2
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-06-07T19:00:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 44d15bba-6471-4030-ae8a-339994eb6fd0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-31T18:52:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 29579835-63db-4481-b347-52f1852e0eb9 # Featured Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd264ccd-7898-49b7-9476-1095b3c6b2ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-31T18:52:51+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: af6550e1-b206-4dcc-a2ff-a847082b77bc # Body
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e25caf86-a917-4d74-bd83-09fd75ea4ba0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-31T19:51:57+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 76c53e19-a060-468b-9dcb-6f2874cdcde4 # Resource Links
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fd8e9bb-727c-4a34-ae0b-d1cda3812cb6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-01T16:02:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 895989d9-cefc-4582-bbad-6736c0c471b8 # Post Images
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a14ea64-cfdb-484d-a052-3a738e5f5869
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-07T18:06:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c8ae7352-3ab5-47e7-b586-a001fbe07430 # Project Types
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 804830c6-96da-4912-9671-8caa32eb58ad
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-07T12:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 52d25c97-f091-4cfb-84f6-e2529d60f743 # Post Categories
            handle: null
            instructions: null
            label: Categories
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4db1153e-57dc-45d1-8d5c-4f88c7d8f2ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-07T12:00:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5cfa4a6e-5fa2-43f3-a646-d35ea81d5d63 # Post Tags
            handle: null
            instructions: null
            label: Tags
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 736f190c-e3e7-4dfb-a456-f9bdd5558308
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-07T19:00:40+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: dd7373ee-b1ce-4c8d-815d-03cfaed9bd88 # Design Source
            handle: null
            instructions: null
            label: 'Design Source'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1d2c1b4-217a-4698-ba0e-a5c47b8bcb3f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ba352f3f-65b1-4101-a8a0-11df5935be93
        userCondition: null
    thumbFieldKey: null
handle: post
hasTitleField: true
icon: null
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
