defaultPlacement: end
fieldLayouts:
  1b9b578a-d92d-42d0-955e-bd260fff1f4a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: ae0f94af-08c6-4c7d-8755-7b54e29c8c55
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-22T00:00:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 3cb6b6d4-4bf5-4f4a-a9dc-0ef1fdbe6f2a
            handle: null
            instructions: null
            label: 'Colour Pair'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d4f9b53-6d35-4f3f-a70f-8e2f2e4f4d2b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f11f1ec7-2444-4bc4-9df8-b0f6d6e9d9f1
        userCondition: null
    thumbFieldKey: null
handle: projectTypes
name: 'Project Types'
siteSettings:
  fe57eae0-97a1-40b3-bf35-42f69f3d1203: # Box of Dragons
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 3aa14d97-f744-4b52-a661-fb4971781f9e
