columnSuffix: null
handle: directory
instructions: null
name: Directory
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - /
        -
          - value
          - ''
        -
          - icon
          - bars
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - KnitStitch
        -
          - value
          - https://www.knitstitch.misssponto.me.uk
        -
          - icon
          - hat-winter
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
