columnSuffix: null
handle: homeCardLink
instructions: 'Optional link for the card, such as /posts or /holiday-2026.'
name: 'Home Card Link'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 1
  multiline: false
  placeholder: /your-page
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
