columnSuffix: null
handle: homeCards
instructions: null
name: 'Home Cards'
searchable: false
settings:
  createButtonLabel: 'Add card'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b1f1f6d9-8df9-4c8c-9c38-f5f055b6db00 # Home Card
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
