columnSuffix: null
handle: instructions
instructions: null
name: Instructions
searchable: false
settings:
  createButtonLabel: 'Add section'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - e507c3b9-be64-43ba-8f46-f3630adbaa68 # Instruction Section
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
