columnSuffix: null
handle: instructionSteps
instructions: null
name: 'Instruction Steps'
searchable: false
settings:
  createButtonLabel: 'Add step'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - e658df5a-6730-4006-8252-088fed617ae2 # Instruction Step
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
