columnSuffix: null
handle: instructionStepTexts
instructions: null
name: 'Text Blocks'
searchable: false
settings:
  createButtonLabel: 'Add text block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - ade117cc-4dd2-4d57-a69a-4742a3be244d # Text Block
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
