columnSuffix: null
handle: postTags
instructions: null
name: 'Post Tags'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: false
  showSiteMenu: false
  source: 'taggroup:26b22827-3880-4070-a7dc-a3a2c7ca6815' # Tags
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
