columnSuffix: null
handle: projectsArchiveHeading
instructions: 'Main heading shown on the /posts archive page.'
name: 'Projects Archive Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 1
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
