columnSuffix: null
handle: projectsArchiveMetaDescription
instructions: 'Meta description used on the /posts archive page.'
name: 'Projects Archive Meta Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
