columnSuffix: null
handle: projectTypes
instructions: null
name: 'Project Types'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: false
  source: 'group:1814cb28-7cb6-4a76-a95b-6b0829126ccc' # Project Types
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
