columnSuffix: null
handle: projectsArchiveSidebarIntro
instructions: 'Short introduction shown above the archive filters.'
name: 'Projects Archive Sidebar Intro'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
