columnSuffix: null
handle: siteNavUrl
instructions: 'URL for the top-level item. Leave blank if it should only open a submenu.'
name: 'Navigation URL'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 1
  multiline: false
  placeholder: /
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
