columnSuffix: null
handle: siteNavigation
instructions: 'Top navigation links shown site-wide.'
name: 'Site Navigation'
searchable: false
settings:
  addRowLabel: 'Add a link'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
  defaults:
    -
      __assoc__:
        -
          - col1
          - Home
        -
          - col2
          - /
        -
          - rowId
          - 7a39f7c8-5d75-49b3-92eb-f6f8f3e2ff01
    -
      __assoc__:
        -
          - col1
          - 'Completed Projects'
        -
          - col2
          - /posts
        -
          - rowId
          - 8cc6b4cf-5142-4f57-9c95-fb0c8d0d9e6a
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
