columnSuffix: null
handle: siteNavChildren
instructions: 'Optional submenu links shown beneath this top-level item.'
name: 'Submenu Links'
searchable: false
settings:
  addRowLabel: 'Add submenu link'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Label
            -
              - handle
              - label
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - URL
            -
              - handle
              - url
            -
              - width
              - ''
            -
              - type
              - url
  defaults: []
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
