columnSuffix: null
handle: siteNavigation
instructions: 'Top navigation links shown site-wide, with optional submenu links.'
name: 'Site Navigation'
searchable: false
settings:
  createButtonLabel: 'Add navigation item'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 11e3f2ab-984e-4f93-9f70-d9bcfdf52828 # Navigation Item
        -
          - group
          - Navigation
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
