dateModified: 1782133259
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      page: Entries
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:7e05d885-8a22-4531-b57e-12f3e9d7f469' # Posts
      page: Entries
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      page: Entries
      tableAttributes:
        - status
        - link
      type: native
elementSourcesPages:
  craft\elements\Entry:
    Entries:
      icon: amp-guitar
email:
  fromEmail: gothic-chav@hotmail.co.uk
  fromName: 'Box of Dragons'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  Uploads:
    hasUrls: true
    name: uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    2c8cda87-8dae-4200-90ab-ee9059f6bcc2: 'Home Card Link' # Home Card Link
    2dbde0bb-7009-42ef-a06b-d3e854039012: 'Public Schema' # Public Schema
    3a06dc53-056c-4456-af7e-d0a31bfa07b5: 'Submenu Links' # Submenu Links
    4fb2b3ef-47c1-4d31-836a-5f8f7f0f8c2f: Home # Home
    5b3aea98-6154-4441-b434-0ccff8aabf4c: 'Home Intro' # Home Intro
    5cfa4a6e-5fa2-43f3-a646-d35ea81d5d63: 'Post Tags' # Post Tags
    5d7b7d6f-0d18-4dc2-988c-01f4d2f0b4f4: 'Home Card Link' # Home Card Link
    6a47cd07-ec9e-460f-999f-081f64ceeb62: 'Projects Archive' # Projects Archive
    6d5f633b-173a-4a21-bbee-cb8590d766f1: 'Site Name' # Site Name
    7a2cc7d6-44ed-42f9-ba98-82d4a58c0590: 'Projects Archive Sidebar Intro' # Projects Archive Sidebar Intro
    7c6b1435-4697-4f69-89da-0f52489f40c7: 'Site Header' # Site Header
    7e05d885-8a22-4531-b57e-12f3e9d7f469: Posts # Posts
    11e3f2ab-984e-4f93-9f70-d9bcfdf52828: 'Navigation Item' # Navigation Item
    26b22827-3880-4070-a7dc-a3a2c7ca6815: Tags # Tags
    37ace21d-9659-4ab9-9eb8-4f9baf881c29: 'Navigation Label' # Navigation Label
    52d25c97-f091-4cfb-84f6-e2529d60f743: 'Post Categories' # Post Categories
    56b64bf1-40b8-4808-a076-f845aced2527: 'Post Images' # Post Images
    76c53e19-a060-468b-9dcb-6f2874cdcde4: 'Resource Links' # Resource Links
    79c2cc19-c161-4916-b859-98f211c101b5: 'Projects Archive Heading' # Projects Archive Heading
    101aedec-3a1b-481f-b8ae-4522481936b6: 'Home Card Text' # Home Card Text
    501afdad-7ccc-463d-9bba-7fae94a5d8c3: 'Box of Dragons' # Box of Dragons
    672dca83-46cd-4ac4-aa4b-65e9d7430d7a: 'Home Card Image' # Home Card Image
    988f6d4d-f99d-4996-a981-d3f4e7569f59: Directory # Directory
    1814cb28-7cb6-4a76-a95b-6b0829126ccc: 'Project Types' # Project Types
    2380f0b5-e90e-4c9a-a859-2642a8780e71: 'Markdown Page' # Markdown Page
    392516be-39ef-42d6-af30-f84123d033d9: 'Site Navigation' # Site Navigation
    895989d9-cefc-4582-bbad-6736c0c471b8: 'Post Images' # Post Images
    29579835-63db-4481-b347-52f1852e0eb9: 'Featured Image' # Featured Image
    ad486461-8a57-4496-bf13-b475d020d92f: 'Navigation URL' # Navigation URL
    af6550e1-b206-4dcc-a2ff-a847082b77bc: Body # Body
    b0fd993f-201f-421a-973d-1c61f5c12903: 'Markdown Source URL' # Markdown Source URL
    b1f1f6d9-8df9-4c8c-9c38-f5f055b6db00: 'Home Card' # Home Card
    b38efefa-beb0-4839-9347-42377ec6746d: 'Projects Archive Meta Description' # Projects Archive Meta Description
    c8ae7352-3ab5-47e7-b586-a001fbe07430: 'Project Types' # Project Types
    c502d161-c8da-41a1-be35-09304ce9b1ff: 'Misc Images' # Misc Images
    c2347409-b4ee-421d-8079-9c9ae09e7a1d: Post # Post
    d7835db0-9bc7-4ee6-8ad8-acd09625daf0: Post # Post
    da5d8ca2-8f7f-4375-96fb-53ffeed1a4a2: Categories # Categories
    dd7373ee-b1ce-4c8d-815d-03cfaed9bd88: 'Design Source' # Design Source
    e7c37c0b-1ba6-4e81-ab3c-5098fcf9218d: 'Home Heading' # Home Heading
    e937e671-7ee5-4111-8c6f-440df087bae6: 'Home Cards' # Home Cards
    fbd053e2-d25f-4b04-9271-c37fc5366685: 'Markdown Page' # Markdown Page
    fc08b7eb-9365-4b5b-98fd-193abc9cc1bb: 'Design Sources' # Design Sources
    fd9b9dfd-058f-4810-a86c-3f74aa2d8f4c: 'Projects Archive' # Projects Archive
    fe57eae0-97a1-40b3-bf35-42f69f3d1203: 'Box of Dragons' # Box of Dragons
plugins:
  cookie-consent-banner:
    edition: standard
    enabled: true
    schemaVersion: 1.0.3
system:
  edition: solo
  live: true
  name: 'Box of Dragons'
  schemaVersion: 5.10.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
