fieldLayouts:
  b9386c15-93a3-406e-bb7f-950224875760:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-06-01T16:33:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6d5f633b-173a-4a21-bbee-cb8590d766f1 # Site Name
            handle: null
            instructions: null
            label: 'Site Name'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 899fa8a8-1ad3-4f86-b1b2-048dd871db50
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-06-01T16:33:42+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 392516be-39ef-42d6-af30-f84123d033d9 # Site Navigation
            handle: null
            instructions: null
            label: Navigation
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 373d3959-07ce-4d65-acd4-671dc62599d1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d6c4efb6-9421-48c8-89b4-6a9f1c15ef1e
        userCondition: null
    thumbFieldKey: null
handle: siteHeader
name: 'Site Header'
sortOrder: 2
