defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7da26bdd-69b5-40b9-8fb9-99992183e3fa # Change Log
handle: changeLogPage
maxAuthors: 1
minAuthors: 1
name: 'Change Log'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fe57eae0-97a1-40b3-bf35-42f69f3d1203: # Box of Dragons
    enabledByDefault: true
    hasUrls: true
    template: _entries/change-log-page.twig
    uriFormat: change-log
type: single
