defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fbd053e2-d25f-4b04-9271-c37fc5366685 # Markdown Page
handle: markdownPage
maxAuthors: 1
minAuthors: 1
name: 'Markdown Page'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  fe57eae0-97a1-40b3-bf35-42f69f3d1203: # Box of Dragons
    enabledByDefault: true
    hasUrls: true
    template: _entries/markdown-page.twig
    uriFormat: '{directory}/{slug}'
type: channel
